version: '3.8'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: trademark_journals
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - DB_URL=postgresql://admin:admin@db:5432/trademark_journals
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    command: tail -f /dev/null

volumes:
  db_data:
